const Map<String, String> specificTokenNames = {
  'dAAPL': 'Apple',
  'dAMZN': 'Amazon',
  'dBABA': 'Alibaba',
  'dCOIN': 'Coinbase',
  'dGME': 'Gamestop',
  'dGOOGL': 'Google',
  'dNVDA': 'Nvidia',
  'dPLTR': 'Palantir',
  'dTSLA': 'Tesla',
  'dARKK': 'New Tech.',
  'dGLD': 'Gold',
  'dSLV': 'Silver',
  'dPDBC': 'Commodities',
  'dQQQ': 'Nasdaq',
  'dSPY': 'S&P',
  'dTLT': 'US Treas. 20Y',
  'dURTH': 'MSCI World',
  'dVNQ': 'Real Estate',
  'dEEM': 'Emerg.Markets',
  'dFB': 'Facebook',
  'dMSFT': 'Microsoft',
  'dNFLX': 'Netflix',
  'dVOO': 'S&P ETF',
  'dDIS': 'Disney',
  'dMSTR': 'Microstrat.',
  'dMCHI': 'MSCI China',
  'dINTC': 'Intel',
  'dBRK.B': 'Berkshire',
  'dPYPL': 'Paypal',
  'dPG': 'Procter&Gm.',
  'dKO': 'CocaCola',
  'dCS': 'Credit Suisse',
  'dSAP': 'SAP SE',
  'dGSG': 'Commod. ETF',
  'dURA': 'Uran ETF',
  'dXOM': 'Exxon',
  'dGOVT': 'US Treas. ETF',
  'dTAN': 'Solar ETF',
  'dPPLT': 'Platinum ETF',
  'dJNJ': 'Johnson & J.',
  'dDAX': 'Dax ETF',
  'dADDYY': 'Adidas',
  'dGS': 'Goldm. Sachs',
  'dUNG': 'US Gas Fund',
  'dUSO': 'US Oil Fund',
  'dWMT': 'Walmart',
  'dUL': 'Unilever',
  'dARKX': 'Space ETF',
  'dVBK': 'Sm.Caps ETF',
  'dXLRE': 'Real Est. ETF',
  'dXLE': 'Energy Fund',
  'dNSRGY': 'Nestle',
  'dSH': 'Short S&P ETF',
  'dSHEL': 'Shell',
  'dBITI': 'BTC Inv ETF',
};