import 'dart:ui';

import 'package:defi_wallet/mixins/theme_mixin.dart';
import 'package:defi_wallet/widgets/buttons/accent_button.dart';
import 'package:defi_wallet/widgets/buttons/new_primary_button.dart';
import 'package:defi_wallet/widgets/dotted_tab.dart';
import 'package:defi_wallet/widgets/responsive/stretch_box.dart';
import 'package:flutter/material.dart';

class ConnectLedgerFirstScreen extends StatefulWidget {
  final void Function() callback;

  const ConnectLedgerFirstScreen({Key? key, required this.callback})
      : super(key: key);

  @override
  State<ConnectLedgerFirstScreen> createState() =>
      _ConnectLedgerFirstScreenState();
}

class _ConnectLedgerFirstScreenState extends State<ConnectLedgerFirstScreen>
    with ThemeMixin {
  String subtitleText =
      'When you connect Jellywallet to your ledger device, your recovery phrase is not stored or generated by Jellywallet.';
  String titleText = '1.';

  @override
  Widget build(BuildContext context) {
    return Center(
      child: StretchBox(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Image.asset(
              'assets/images/defi_no_seed_phrase.png',
              width: 262.94,
              height: 236.44,
            ),
            Container(
              child: Column(
                children: [
                  DottedTab(
                    tabLenth: 4,
                    selectTabIndex: 1,
                  ),
                  SizedBox(
                    height: 19,
                  ),
                  Text(
                    '$titleText Connect Ledger',
                    style: Theme.of(context).textTheme.headline3,
                  ),
                  SizedBox(
                    height: 8,
                  ),
                  Container(
                    height: 105,
                    child: Text(
                      subtitleText,
                      style: Theme.of(context).textTheme.headline5!.copyWith(
                            color: Theme.of(context)
                                .textTheme
                                .headline5!
                                .color!
                                .withOpacity(0.6),
                          ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        width: 104,
                        child: AccentButton(
                          callback: () {
                            Navigator.pop(context);
                          },
                          label: 'Cancel',
                        ),
                      ),
                      NewPrimaryButton(
                        width: 104,
                        callback: () {
                          this.widget.callback();
                        },
                        title: 'Next',
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
